version:  "3.2"
services:
  https-portal:
    image:  steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - static-content:/static:ro
      - ./nginx/nginx.conf:/var/lib/nginx-conf/localhost.ssl.conf.erb:ro
    environment:
      DOMAINS:  "localhost -> http://webapp:80"
      STAGE:  "production"
      FORCE_RENEW:  "true"
    networks:
      - bridged
    depends_on:
      - "webapp"
    
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    # restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=password123*
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      - bridged

  webapp:
    image: matomo
    # restart: always
    volumes:
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
    ports:
      - "8080:80"
    networks:
      - bridged
volumes:
  db:
  matomo:
  static-content:

networks:
  bridged: